# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
pool:
  name: 'Default'
variables:
  MAVEN_OPTS: '-Xmx3072m'

stages:
- stage: Build
  displayName: 'Build Mule Application'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - task: Maven@4
      displayName: 'Build Mule Package'
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '$(MAVEN_OPTS)'
        javaHomeOption: 'path'
        jdkDirectory: '/Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'clean package'
        options: '-DskipTests -U'

- stage: PublishExchange
  displayName: 'Publish Package to Anypoint Exchange'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: PublishExchangeJob
    displayName: 'Publish to Exchange'
    steps:
    - task: Maven@4
      displayName: 'Publish Mule App to Exchange'
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '$(MAVEN_OPTS)'
        javaHomeOption: 'path'
        jdkDirectory: '/Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        goals: 'deploy'
        options: >
          -DskipTests
          -U
          -Danypoint.username=$(ANYPOINT_PLATFORM_USERNAME)
          -Danypoint.password=$(ANYPOINT_PLATFORM_PASSWORD)

- stage: Deploy
  displayName: 'Deploy Mule Application'
  dependsOn: PublishExchange
  condition: succeeded()
  jobs:
  - job: DeployJob
    displayName: 'Deploy Job'
    steps:
    - task: Maven@4
      displayName: 'Deploy to Runtime Manager'
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '$(MAVEN_OPTS)'
        javaHomeOption: 'path'
        jdkDirectory: '/Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        goals: 'mule:deploy'
        options: >
          -DskipTests
          -U
          -DmuleDeploy
          -Danypoint.username=$(ANYPOINT_PLATFORM_USERNAME)
          -Danypoint.password=$(ANYPOINT_PLATFORM_PASSWORD)
          -Dapi.id=$(API_ID)
          -Danypoint.platform.client_id=$(ANYPOINT_PLATFORM_CLIENT_ID)
          -Danypoint.platform.client_secret=$(ANYPOINT_PLATFORM_CLIENT_SECRET)