CREATE TABLE CLAIMS (
    CLAIM_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    CLAIM_NUMBER VARCHAR(50) NOT NULL UNIQUE,
    POLICY_NUMBER VARCHAR(50) NOT NULL,
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    CLAIM_TYPE VARCHAR(50) NOT NULL,
    CLAIM_STATUS VARCHAR(30) NOT NULL,
    CLAIM_AMOUNT DECIMAL(18,2) NULL,
    CURRENCY VARCHAR(10) DEFAULT 'HKD',
    INCIDENT_DATE DATE NULL,
    SUBMITTED_DATE DATETIME2 DEFAULT SYSDATETIME(),
    LAST_UPDATED_DATE DATETIME2 DEFAULT SYSDATETIME(),
    CREATED_BY VARCHAR(100) NULL,
    UPDATED_BY VARCHAR(100) NULL
);

CREATE TABLE CLAIM_DETAILS (
    CLAIM_DETAIL_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    CLAIM_ID BIGINT NOT NULL,
    DESCRIPTION NVARCHAR(MAX) NULL,
    HOSPITAL_NAME NVARCHAR(200) NULL,
    DIAGNOSIS NVARCHAR(500) NULL,
    REMARKS NVARCHAR(MAX) NULL,
    CREATED_DATE DATETIME2 DEFAULT SYSDATETIME(),

    CONSTRAINT FK_CLAIM_DETAILS_CLAIMS
        FOREIGN KEY (CLAIM_ID) REFERENCES CLAIMS(CLAIM_ID)
);

CREATE TABLE CLAIM_DOCUMENTS (
    DOCUMENT_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    CLAIM_ID BIGINT NOT NULL,
    FILE_NAME VARCHAR(255) NOT NULL,
    FILE_TYPE VARCHAR(50) NULL,
    FILE_SIZE BIGINT NULL,
    FILE_PATH VARCHAR(1000) NULL,
    DOCUMENT_STATUS VARCHAR(30) DEFAULT 'UPLOADED',
    UPLOADED_BY VARCHAR(100) NULL,
    UPLOADED_DATE DATETIME2 DEFAULT SYSDATETIME(),

    CONSTRAINT FK_CLAIM_DOCUMENTS_CLAIMS
        FOREIGN KEY (CLAIM_ID) REFERENCES CLAIMS(CLAIM_ID)
);

CREATE TABLE CLAIM_PAYMENTS (
    PAYMENT_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    CLAIM_ID BIGINT NOT NULL,
    PAYMENT_REFERENCE VARCHAR(100) NOT NULL UNIQUE,
    PAYMENT_METHOD VARCHAR(50) NULL,
    PAYMENT_STATUS VARCHAR(30) NOT NULL,
    PAYMENT_AMOUNT DECIMAL(18,2) NOT NULL,
    CURRENCY VARCHAR(10) DEFAULT 'HKD',
    PROVIDER_NAME VARCHAR(50) NULL,
    TRANSACTION_ID VARCHAR(100) NULL,
    PAYMENT_DATE DATETIME2 NULL,
    CREATED_DATE DATETIME2 DEFAULT SYSDATETIME(),

    CONSTRAINT FK_CLAIM_PAYMENTS_CLAIMS
        FOREIGN KEY (CLAIM_ID) REFERENCES CLAIMS(CLAIM_ID)
);

CREATE TABLE API_REQUEST_AUDIT (
    AUDIT_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    CORRELATION_ID VARCHAR(100) NULL,
    API_NAME VARCHAR(100) NOT NULL,
    HTTP_METHOD VARCHAR(10) NOT NULL,
    REQUEST_PATH VARCHAR(500) NOT NULL,
    CUSTOMER_ID VARCHAR(50) NULL,
    CLAIM_NUMBER VARCHAR(50) NULL,
    RESPONSE_STATUS_CODE INT NULL,
    REQUEST_TIMESTAMP DATETIME2 DEFAULT SYSDATETIME(),
    RESPONSE_TIMESTAMP DATETIME2 NULL,
    SOURCE_SYSTEM VARCHAR(100) NULL,
    CLIENT_ID VARCHAR(100) NULL
);

CREATE TABLE API_ERROR_LOG (
    ERROR_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    CORRELATION_ID VARCHAR(100) NULL,
    API_NAME VARCHAR(100) NOT NULL,
    ERROR_CODE VARCHAR(50) NOT NULL,
    ERROR_MESSAGE NVARCHAR(MAX) NULL,
    ERROR_TYPE VARCHAR(100) NULL,
    HTTP_STATUS_CODE INT NULL,
    STACK_TRACE NVARCHAR(MAX) NULL,
    CREATED_DATE DATETIME2 DEFAULT SYSDATETIME()
);

CREATE TABLE CLAIM_EVENTS (
    EVENT_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    CLAIM_ID BIGINT NOT NULL,
    CLAIM_NUMBER VARCHAR(50) NOT NULL,
    EVENT_TYPE VARCHAR(50) NOT NULL,
    EVENT_STATUS VARCHAR(30) DEFAULT 'PENDING',
    RETRY_COUNT INT DEFAULT 0,
    MAX_RETRY_COUNT INT DEFAULT 3,
    ERROR_MESSAGE NVARCHAR(MAX) NULL,
    CREATED_DATE DATETIME2 DEFAULT SYSDATETIME(),
    UPDATED_DATE DATETIME2 DEFAULT SYSDATETIME(),
    PROCESSED_DATE DATETIME2 NULL,

    CONSTRAINT FK_CLAIM_EVENTS_CLAIMS
        FOREIGN KEY (CLAIM_ID) REFERENCES CLAIMS(CLAIM_ID)
);

CREATE TABLE CLAIM_PROCESSING_HISTORY (
    HISTORY_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    CLAIM_ID BIGINT NOT NULL,
    CLAIM_NUMBER VARCHAR(50) NOT NULL,
    OLD_STATUS VARCHAR(30) NULL,
    NEW_STATUS VARCHAR(30) NOT NULL,
    PROCESSING_STEP VARCHAR(100) NULL,
    REMARKS NVARCHAR(MAX) NULL,
    CREATED_DATE DATETIME2 DEFAULT SYSDATETIME(),

    CONSTRAINT FK_CLAIM_HISTORY_CLAIMS
        FOREIGN KEY (CLAIM_ID) REFERENCES CLAIMS(CLAIM_ID)
);

CREATE INDEX IDX_CLAIMS_POLICY_NUMBER
ON CLAIMS(POLICY_NUMBER);

CREATE INDEX IDX_CLAIMS_CUSTOMER_ID
ON CLAIMS(CUSTOMER_ID);

CREATE INDEX IDX_CLAIMS_STATUS
ON CLAIMS(CLAIM_STATUS);

CREATE INDEX IDX_DOCUMENTS_CLAIM_ID
ON CLAIM_DOCUMENTS(CLAIM_ID);

CREATE INDEX IDX_PAYMENTS_CLAIM_ID
ON CLAIM_PAYMENTS(CLAIM_ID);

CREATE INDEX IDX_AUDIT_CORRELATION_ID
ON API_REQUEST_AUDIT(CORRELATION_ID);

CREATE INDEX IDX_ERROR_CORRELATION_ID
ON API_ERROR_LOG(CORRELATION_ID);

CREATE INDEX IDX_EVENTS_STATUS
ON CLAIM_EVENTS(EVENT_STATUS);

CREATE INDEX IDX_EVENTS_CLAIM_ID
ON CLAIM_EVENTS(CLAIM_ID);

CREATE INDEX IDX_HISTORY_CLAIM_ID
ON CLAIM_PROCESSING_HISTORY(CLAIM_ID);

ALTER TABLE CLAIM_DOCUMENTS ADD
    STORAGE_PROVIDER VARCHAR(50) DEFAULT 'AZURE_BLOB',
    CONTAINER_NAME VARCHAR(100) NULL,
    BLOB_NAME VARCHAR(500) NULL,
    BLOB_URL VARCHAR(1000) NULL,
    CONTENT_TYPE VARCHAR(100) NULL,
    DOCUMENT_REFERENCE_ID VARCHAR(100) NULL,
    CHECKSUM VARCHAR(200) NULL,
    IS_ACTIVE BIT DEFAULT 1;