#%RAML 1.0
title: claimsPortal-XPAPI
description:  Claims Portal API for claim creation, claim retrieval, claim data submission,
  file upload/download, and claim payment processing.Updated host details to de deployed as maahi.claimsportal.com
version: V1
protocols:
  - HTTPS
  - HTTP
baseUri: http://localhost:8081/api/{version}

uses:
  common: libraries/common-types.raml
  traitsLib: libraries/common-traits.raml
  claimsLib: libraries/claims-types.raml
  fileLib: libraries/file-types.raml
  paymentLib: libraries/payment-types.raml
  errorTraits: libraries/error-traits.raml

securedBy:
  - basicAuth
/healthCheck:
  get:
    description: This API will get status of the service running
    responses:
      200:
        body:
          application/json:
            example:
              !include /healthCheckSuccessResponse.json

securitySchemes:
  basicAuth:
    type: Basic Authentication
    description: Basic Authentication or API Manager policy-based authentication.