#%RAML 1.0
title: claimsPortal-XPAPI
description: This API will handle all the claim related handling like requests, endorsements and settlements. Updated host details to de deployed as maahi.claimsportal.com
version: V1
protocols:
  - HTTPS
  - HTTP
baseUri: http://localhost:8081/api/{version}

/healthCheck:
  get:
    description: This API will get status of the service running
    responses:
      200:
        body:
          application/json:
            example:
              !include /healthCheckSuccessResponse.json
          
